version: "3.8"
services:
  glances:
    image: nicolargo/glances:latest
    container_name: glances
    ports:
      - 61208:61208
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GLANCES_OPT=-w
    restart: always
    pid: host
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
