version: "3.8"
services:
  dashy:
    image: lissy93/dashy:latest
    ports:
      - 8080:80
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M # Giới hạn chỉ cho dùng tối đa 256MB RAM